name: ASP.NET Core CI

on: [push, pull_request, release]

jobs:
  build:

    runs-on: windows-latest
    
    steps:      
    - uses: actions/checkout@master
      
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 2.2.108

    - name: Build with dotnet
      run: dotnet build ./src --configuration Release
  
    - name: Create artifacts
      uses: actions/upload-artifact@master
      with:
        name: Alex
        path: ./src/Alex/bin
