name: .NET Core

on:
  push:
    branches: master

jobs:
  nuget:
    name: Publish to NuGET
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/Alex.MoLang/Alex.MoLang.csproj
        PACKAGE_NAME: Alex.MoLang
        NUGET_KEY: ${{secrets.NUGET_PUBLISH_KEY}}
        VERSION_STATIC: '1.0.${{github.run_id}}'
        
  package:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rid: [linux-x64, osx-x64, win-x64]
        artifact: ['Linux Binaries', 'MacOS Binaries', 'Windows Binaries']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 5.0.x
    
    - name: Get short SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
    - name: Build
      run: dotnet publish --configuration Release -o "build" --version-suffix ${{steps.vars.outputs.sha_short}} -r ${{matrix.rid}} /p:PublishReadyToRun=false /p:TieredCompilation=false --self-contained
      working-directory: src/Alex

    #- name: Set executable permissions
    #  working-directory: src/Alex/build
    #  run: chmod +x Alex

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ${{matrix.artifact}}
        # Directory containing files to upload
        path: "src/Alex/build"